### ISSUE TITLE
Implement Dynamic RPC pick handler

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/rpc-handler#3]
We want to use Chainlist's list of RPC endpoints. Create a class that will handle this:
- We should import the Chainlist repository as a submodule to stay in sync.
- The URLs should be tested upon initialization (i.e. page load) via `Promise.race`
- The class should rank sort based on latency. 
- The class should drop failed endpoints. 
- The class should have a wrapper method to make a network request using the optimal RPC endpoint, and to drop it/automatically rotate to the next best from the list if a network request fails. 

We will use this across all of our products that require RPC calls so: 
- Make a standalone and polymorphic (frontend and backend compatible) npm module.
- Make sure to have unit tests in Jest.

### Original Spec

The code should drop bad RPCs dynamically. I had a prototype implemented where it would delete from local storage if there was an error for example. Later in the code it would only select from local storage options. 

> This blacklist idea doesn't seem like a robust approach. We can merge it in but it should be handled dynamically. I think I implemented this in an unstable manner on my branch, I vaguely recall.

_Originally posted by @pavlovcik in https://github.com/ubiquity/pay.ubq.fi/pull/169#discussion_r1502430625_

**Comment by molecula451** [comment]
looking at the committer solution indeed this blacklist it's not a good idea because it's manually blacklisting each RPC it's senseless

**Comment by Keyrxng** [comment]
this is resolved in ubiquity/pay.ubq.fi#177, the temporary fix was preventing the claim button from flickering on the live portal (since only gnosis is used right now I only blacklisted those that were failing), senseless but effective

We can't know if an rpc call is going to fail until it's attempted, those that fail return no data through `` const { data } = await API.post("", RPC_BODY); ``. In logging ``status`` and ``statusText`` you only get ``200`` responses. Although in testing mainnet (49 rpcs on ``sync-erc-permits``) some fail but may succeed later whereas the two I added for gnosis makeup three failed calls which I haven't saw succeed once.

So we can't dynamically pop RPCs from the list until they've been tried at least once and even then with no data returned there are no bad latency entries to pop either

I think filtering out the ``tracking: "yes"`` category should be considered at least. ``none``-only takes mainnet down to 18 and gnosis down to 7. ``Limited`` adds 4 more to gnosis and 7 for mainnet.

chainlist/extraRpcs.js
```yml
      {
        url: "https://eth.nodeconnect.org/",
        tracking: "yes",
        trackingDetails: privacyStatement.nodeconnect,
      },
      {
        url: "https://rpc.polysplit.cloud/v1/chain/1",
        tracking: "none",
        trackingDetails: privacyStatement.polysplit,
      },
       {
      	url: "https://eth-mainnet.diamondswap.org/rpc",
      	tracking: "limited",
      	trackingDetails: privacyStatement.diamondswap,
      },
```
